### ISSUE TITLE
替换Clover后重复进Recovery

### ISSUE THREAD

**Issue by stedio** [davidkathy/Surface-Pro6-OpenCore#2]
感谢分享。我也是更新了微软的firmware 之后Clover引导进不去了。

请问可以保留之前的系统直接替换Clover么？我替换了Clover的引导文件，现在开机可以看见OC的引导。但是选择osx的盘符，出现苹果然后机器就重启然后就进入osx的recovery了。貌似是直接进入的苹果的恢复分区？

试验了很多次，发现安装10.14 第一次重启后就进不去系统了，会提示loadImage Failed - Unsupported，起初怀疑是APFS系统驱动问题，试了好几个都不行。

又试验了10.15，很奇怪这个版本可以顺利安装和启动。请问大佬使用的是哪个版本的系统呢？

**Comment by stedio** [comment]
把之前的mac分区格式了准备重新装，但是现在用u盘启动，选osx base system, 苹果闪一下直接自动重启然后进windows了。。。太诡异了。请问EFI文件需要为安装做什么改动么？

**Comment by davidkathy** [comment]
for 10.15.6

**Comment by stedio** [comment]
> for 10.15.6

Thanks for the reply. 

请问如果想安装10.14应该在哪里做改动呢？多谢🙏🏻

**Comment by stedio** [comment]
解决了，更改了securemode 的机器版本就可以了

**Comment by davidkathy** [comment]
可以帮忙更新下修改事项不？我更新到list中。

**Comment by stedio** [comment]
> 可以帮忙更新下修改事项不？我更新到list中。

Misc -> Security -> SecureBootModel

每个Model 都有最低的系统要求，改为 'j213' 可以支持10.14

更多的设置可以参考 https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel

**Comment by stedio** [comment]
> 可以帮忙更新下修改事项不？我更新到list中。

Misc -> Security -> SecureBootModel 改成低版本的Mac，比如 ‘j213’ 就可以支持10.14.

**Comment by bin5345** [comment]
我更改了j213仍然进不了系统。系统是10.14.6

**Comment by davidkathy** [comment]
> 我更改了j213仍然进不了系统。系统是10.14.6

我测试了下，可以进入安装界面了。如果进不了系统，你可以先吧kext和aml这些先移除掉一些不是必须的，测试验证下。

**Comment by bin5345** [comment]
> > 我更改了j213仍然进不了系统。系统是10.14.6
> 
> 我测试了下，可以进入安装界面了。如果进不了系统，你可以先吧kext和aml这些先移除掉一些不是必须的，测试验证下。

 我重新安装了10.15.6，触摸板不正常，电源按键不正常。原来的腾达u12无线网卡驱动不了

**Comment by davidkathy** [comment]
> > > 我更改了j213仍然进不了系统。系统是10.14.6
> > 
> > 
> > 我测试了下，可以进入安装界面了。如果进不了系统，你可以先吧kext和aml这些先移除掉一些不是必须的，测试验证下。
> 
> 我重新安装了10.15.6，触摸板不正常，电源按键不正常。原来的腾达u12无线网卡驱动不了

触控使用正常，无法设置。 电源按键和休眠功能，还在修改中。 无线网卡，看看驱动是否正常，10.15 很多无线网卡驱动异常，建议使用COMFAST CF-915AC、 COMFAST CF-811AC

**Comment by bin5345** [comment]
> > > > 我更改了j213仍然进不了系统。系统是10.14.6
> > > 
> > > 
> > > 我测试了下，可以进入安装界面了。如果进不了系统，你可以先吧kext和aml这些先移除掉一些不是必须的，测试验证下。
> > 
> > 
> > 我重新安装了10.15.6，触摸板不正常，电源按键不正常。原来的腾达u12无线网卡驱动不了
> 
> 触控使用正常，无法设置。 电源按键和休眠功能，还在修改中。 无线网卡，看看驱动是否正常，10.15 很多无线网卡驱动异常，建议使用COMFAST CF-915AC、 COMFAST CF-811AC

非常感谢你的回复和指导！现在系统还是不错。存在问题：1、触控板如果只用oc的驱动，有鼠标轻触功能，但没有手势功能。如果放两个kext驱动到L/E目录下重建缓存，有了手势有没有了轻触的功能，以前的10.14.6的触摸板真完美。2、冷开机还是黑屏，要接外屏。3、电源键、音量键还不起作用。

**Comment by bin5345** [comment]
> > > > 我更改了j213仍然进不了系统。系统是10.14.6
> > > 
> > > 
> > > 我测试了下，可以进入安装界面了。如果进不了系统，你可以先吧kext和aml这些先移除掉一些不是必须的，测试验证下。
> > 
> > 
> > 我重新安装了10.15.6，触摸板不正常，电源按键不正常。原来的腾达u12无线网卡驱动不了
> 
> 触控使用正常，无法设置。 电源按键和休眠功能，还在修改中。 无线网卡，看看驱动是否正常，10.15 很多无线网卡驱动异常，建议使用COMFAST CF-915AC、 COMFAST CF-811AC

非常感谢你的回复和指导！现在系统还是不错。存在问题：1、触控板如果只用oc的驱动，有鼠标轻触功能，但没有手势功能。如果放两个kext驱动到L/E目录下重建缓存，有了手势有没有了轻触的功能，以前的10.14.6的触摸板真完美。2、冷开机还是黑屏，要接外屏。3、电源键、音量键还不起作用。

**Comment by bin5345** [comment]
已经升级到Big sur 11.2.3，没有任何问题。非常喜欢Big sur到界面。

**Comment by davidkathy** [comment]
> 已经升级到Big sur 11.2.3，没有任何问题。非常喜欢Big sur到界面。

我还没有升级，再看电源按键和电量管理相关的资料，不知道big sur后电量管理是否有变化。

其实好多问题都是软件调试就可以解决的，apple music，imessage，siri等等，除了Wi-Fi和Camera导致的部分不能使用，基本上看起来可以正常使用了。

**Comment by bin5345** [comment]
冷启动Big sur，SDcard正常。如果从win10重启到Big sur系统，找不到SDcard。
