### ISSUE TITLE
黑屏问题

### ISSUE THREAD

**Issue by luhua98989898** [davidkathy/Surface-Pro6-OpenCore#3]
老大你黑屏的问题解决了吗

**Comment by davidkathy** [comment]
> 老大你黑屏的问题解决了吗

这段时间事情比较忙，黑屏问题一直没找到头绪呢，本来以为与HDMI解决问题有关系，但是我回退到原来测试的config后，发现冷开机黑屏现象依旧会发生，请多等几天，等工作不太忙的时候，研究研究。（我现在每天也是，开机windows后，重启进入macos  :(   ）
