### ISSUE TITLE
V1.2 更新后Windows 蓝屏引导出错

### ISSUE THREAD

**Issue by stedio** [davidkathy/Surface-Pro6-OpenCore#4]
更新1.2后Windows 无法引导，提示Windows run into a problem，无限重启。Mac Os 引导一切正常。

**Comment by davidkathy** [comment]
remove SSDT-XOSI.aml in the config.plist. The mistake was create by this file,maybe.

**Comment by stedio** [comment]
XOSL is not included in V.1.2's config.

Replacing the booter section with v. 1.1 fixed the problem. Not sure which quirk causes the issue.
