### ISSUE TITLE
无法连接4k显示器

### ISSUE THREAD

**Issue by ctrlself** [davidkathy/Surface-Pro6-OpenCore#5]
大佬您好，输出4k显示器只会显示2k，请问有办法解决吗
另外，微软docker音频无法正常输出

**Comment by davidkathy** [comment]
没有4K的显示器，没有办法进行测试呢。 我是DP转HDMI，理论上4K应该没问题。有时候还要看下线材是否支持4K输出

docker 无法音频，可能与docker的驱动版本有关系
