### ISSUE TITLE
关于电量显示、网卡蓝牙的想法

### ISSUE THREAD

**Issue by wqianglxf** [davidkathy/Surface-Pro6-OpenCore#7]
使用Surface pro6 Hackintosh快2年了，由于电量显示问题，最近半年使用率不高。原因是电量恐慌，出差或便捷出门不敢长时间使用。这个问题感觉比WiFi 蓝牙更难受
1.之前我在想可否通过计时器或从ssdt 中找下记录电量的方法，经常很长时间后放弃了，原因在远景有。
2.网卡和蓝牙，软件上不行❌可否硬改，如果有网友拆过机的话，可否提供一下内部是否有空间放置。

**Comment by davidkathy** [comment]
电量显示正常了。

**Comment by wqianglxf** [comment]
> 电量显示正常了。

现在实际使用情况和Windows 相比，同等使用的情况下，哪个系统消耗费电一些？有人测试过吗？
